name: referrals
root: .

#on_project_start:

windows:
  - main:
      layout: vertical
      panes:
        - source venv/bin/activate && ES_SERVER=http://localhost:9200 FLASK_APP=server.py FLASK_ENV=development flask run
        - source venv/bin/activate
